from . import crm_lead
from . import crm_opportunity
from . import crm_customer
from . import crm_activity
from . import crm_stage
from . import crm_tag
from . import crm_partner_enhancement
from . import crm_lead_enhancement
from . import crm_opportunity_enhancement
