from odoo import models, fields, api
from datetime import datetime, timedelta


class CrmPartnerRating(models.Model):
    """Model to track partner ratings and reviews"""
    _name = 'crm.partner.rating'
    _description = 'Partner Rating'
    _order = 'create_date desc'
    
    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='cascade',
    )
    
    rating = fields.Selection(
        [
            ('1', '★ Poor'),
            ('2', '★★ Fair'),
            ('3', '★★★ Good'),
            ('4', '★★★★ Very Good'),
            ('5', '★★★★★ Excellent'),
        ],
        string='Rating',
        required=True,
        tracking=True,
    )
    
    comment = fields.Text(
        string='Comments',
        tracking=True,
    )
    
    rater_id = fields.Many2one(
        'res.users',
        string='Rated by',
        default=lambda self: self.env.user,
        readonly=True,
    )
    
    date_rated = fields.Datetime(
        string='Date Rated',
        default=fields.Datetime.now,
        readonly=True,
    )


class CrmPartnerValue(models.Model):
    """Model to track partner value and customer lifecycle"""
    _name = 'crm.partner.value'
    _description = 'Partner Value Tracking'
    _order = 'date desc'
    
    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='cascade',
    )
    
    value_category = fields.Selection(
        [
            ('revenue', 'Revenue'),
            ('orders', 'Number of Orders'),
            ('frequency', 'Purchase Frequency'),
            ('lifetime', 'Lifetime Value'),
            ('satisfaction', 'Satisfaction Score'),
        ],
        string='Value Category',
        required=True,
    )
    
    value = fields.Float(
        string='Value',
        required=True,
    )
    
    date = fields.Date(
        string='Date',
        default=fields.Date.context_today,
        tracking=True,
    )
    
    note = fields.Text(
        string='Notes',
    )
    
    recorded_by = fields.Many2one(
        'res.users',
        string='Recorded by',
        default=lambda self: self.env.user,
        readonly=True,
    )


class CrmPartnerInfo(models.Model):
    """Separate model to store CRM partner information without inheriting res.partner"""
    _name = 'crm.partner.info'
    _description = 'CRM Partner Information'
    _order = 'partner_id'
    
    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='cascade',
        unique=True,
    )
    
    # CRM Classification
    partner_type = fields.Selection(
        [
            ('prospect', 'Prospect'),
            ('customer', 'Customer'),
            ('vendor', 'Vendor'),
            ('partner', 'Partner'),
            ('lead', 'Lead'),
        ],
        string='Partner Type',
        default='prospect',
        tracking=True,
        help='Classification of the business partner',
    )
    
    # Rating and Value
    average_rating = fields.Float(
        string='Average Rating',
        compute='_compute_average_rating',
        store=False,
    )
    
    rating_count = fields.Integer(
        string='Number of Ratings',
        compute='_compute_rating_count',
        store=False,
    )
    
    partner_value = fields.Float(
        string='Partner Value',
        compute='_compute_partner_value',
        store=False,
        help='Total value generated by this partner',
    )
    
    # Customer Information
    customer_since = fields.Date(
        string='Customer Since',
        tracking=True,
    )
    
    total_spent = fields.Monetary(
        string='Total Spent',
        compute='_compute_total_spent',
        currency_field='company_currency',
        store=False,
    )
    
    company_currency = fields.Many2one(
        'res.currency',
        related='partner_id.company_id.currency_id',
        readonly=True,
    )
    
    # Communication Preferences
    preferred_contact_method = fields.Selection(
        [
            ('email', 'Email'),
            ('phone', 'Phone'),
            ('mobile', 'Mobile'),
            ('whatsapp', 'WhatsApp'),
            ('linkedin', 'LinkedIn'),
        ],
        string='Preferred Contact Method',
        default='email',
        tracking=True,
    )
    
    # Risk Assessment
    credit_risk = fields.Selection(
        [
            ('low', 'Low Risk'),
            ('medium', 'Medium Risk'),
            ('high', 'High Risk'),
        ],
        string='Credit Risk',
        default='medium',
        tracking=True,
    )
    
    # Status Tracking
    last_contact_date = fields.Date(
        string='Last Contact Date',
        readonly=True,
    )
    
    last_activity_date = fields.Date(
        string='Last Activity Date',
        compute='_compute_last_activity_date',
        store=False,
    )
    
    days_since_contact = fields.Integer(
        string='Days Since Contact',
        compute='_compute_days_since_contact',
        store=False,
    )
    
    # Relations
    rating_ids = fields.One2many(
        'crm.partner.rating',
        'partner_id',
        string='Ratings',
    )
    
    value_tracking_ids = fields.One2many(
        'crm.partner.value',
        'partner_id',
        string='Value Tracking',
    )
    
    @api.depends('rating_ids')
    def _compute_average_rating(self):
        for info in self:
            if info.rating_ids:
                ratings = [int(r.rating.split()[0]) for r in info.rating_ids]
                info.average_rating = sum(ratings) / len(ratings)
            else:
                info.average_rating = 0.0
    
    @api.depends('rating_ids')
    def _compute_rating_count(self):
        for info in self:
            info.rating_count = len(info.rating_ids)
    
    @api.depends('value_tracking_ids')
    def _compute_partner_value(self):
        for info in self:
            revenue_value = info.value_tracking_ids.filtered(
                lambda x: x.value_category == 'revenue'
            )
            if revenue_value:
                info.partner_value = sum(v.value for v in revenue_value)
            else:
                info.partner_value = 0.0
    
    @api.depends('partner_id')
    def _compute_total_spent(self):
        for info in self:
            try:
                orders = self.env['sale.order'].search([
                    ('partner_id', '=', info.partner_id.id),
                    ('state', 'in', ['sale', 'done'])
                ])
                info.total_spent = sum(o.amount_total for o in orders)
            except Exception:
                info.total_spent = 0.0
    
    def _compute_last_activity_date(self):
        for info in self:
            try:
                activities = self.env['mail.activity'].search([
                    ('res_model', '=', 'res.partner'),
                    ('res_id', '=', info.partner_id.id),
                ], order='date_deadline desc', limit=1)
                info.last_activity_date = activities.date_deadline if activities else None
            except Exception:
                info.last_activity_date = None
    
    @api.depends('last_contact_date')
    def _compute_days_since_contact(self):
        for info in self:
            if info.last_contact_date:
                days = (fields.Date.context_today(self) - info.last_contact_date).days
                info.days_since_contact = days
            else:
                info.days_since_contact = 0
    
    def action_record_contact(self):
        """Record today's date as last contact date"""
        self.write({
            'last_contact_date': fields.Date.context_today(self),
        })
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Contact Recorded',
                'message': 'Last contact date has been updated',
                'type': 'success',
                'sticky': False,
            }
        }
    
    def action_add_rating(self):
        """Open dialog to add a new rating"""
        return {
            'type': 'ir.actions.act_window',
            'name': 'Add Rating',
            'res_model': 'crm.partner.rating',
            'view_mode': 'form',
            'context': {
                'default_partner_id': self.partner_id.id,
            },
            'target': 'new',
        }
    
    def action_view_ratings(self):
        """View all ratings for this partner"""
        return {
            'type': 'ir.actions.act_window',
            'name': 'Partner Ratings',
            'res_model': 'crm.partner.rating',
            'view_mode': 'tree,form',
            'domain': [('partner_id', '=', self.partner_id.id)],
            'context': {
                'default_partner_id': self.partner_id.id,
            },
        }
    
    def action_view_opportunities(self):
        """View all opportunities related to this partner"""
        return {
            'type': 'ir.actions.act_window',
            'name': 'Opportunities',
            'res_model': 'crm.opportunity',
            'view_mode': 'kanban,list,form',
            'domain': [('partner_id', '=', self.partner_id.id)],
            'context': {
                'default_partner_id': self.partner_id.id,
            },
        }
    
    def action_view_leads(self):
        """View all leads related to this partner"""
        return {
            'type': 'ir.actions.act_window',
            'name': 'Leads',
            'res_model': 'crm.lead',
            'view_mode': 'list,form',
            'domain': [('partner_id', '=', self.partner_id.id)],
        }
    
    def action_view_value_history(self):
        """View partner value tracking history"""
        return {
            'type': 'ir.actions.act_window',
            'name': 'Value History',
            'res_model': 'crm.partner.value',
            'view_mode': 'list,form',
            'domain': [('partner_id', '=', self.partner_id.id)],
            'context': {
                'default_partner_id': self.partner_id.id,
            },
        }

